In [461]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler
from sklearn import metrics
from sklearn.metrics import confusion_matrix
import itertools

### Data Preparation (fake data)

In [462]:
np.random.seed(0)

columns = ['Height', 'Weight']
index = ['person_' + str(x) for x in range(1, 11)]
height_val = [np.random.randint(160, 200) for x in index]
weight_val = [np.random.randint(60, 100) for x in index]
values = zip(height_val, weight_val)

df = pd.DataFrame(values, index=index, columns=columns)
df = df.reset_index()
df['BMI'] = ((df['Weight'] / df['Height']**2 * 10e3) > 25).astype(int)
df

index  Height  Weight  BMI
0   person_1     160      84    1
1   person_2     163      84    1
2   person_3     163      72    1
3   person_4     199      61    0
4   person_5     169      98    1
5   person_6     179      99    1
6   person_7     181      83    1
7   person_8     196      84    0
8   person_9     183      77    0
9  person_10     166      97    1

In [463]:
df.drop('index', axis=1, inplace=True)
df = df.astype(float)
df

Height  Weight  BMI
0   160.0    84.0  1.0
1   163.0    84.0  1.0
2   163.0    72.0  1.0
3   199.0    61.0  0.0
4   169.0    98.0  1.0
5   179.0    99.0  1.0
6   181.0    83.0  1.0
7   196.0    84.0  0.0
8   183.0    77.0  0.0
9   166.0    97.0  1.0

In [517]:
names = df.columns[:2]
scaler = MinMaxScaler()
scaled_df = scaler.fit_transform(df.iloc[:,:2])
scaled_df = pd.DataFrame(scaled_df, columns=names)
scaled_df['BMI'] = df['BMI']
scaled_df

Height    Weight  BMI
0  0.000000  0.605263  1.0
1  0.076923  0.605263  1.0
2  0.076923  0.289474  1.0
3  1.000000  0.000000  0.0
4  0.230769  0.973684  1.0
5  0.487179  1.000000  1.0
6  0.538462  0.578947  1.0
7  0.923077  0.605263  0.0
8  0.589744  0.421053  0.0
9  0.153846  0.947368  1.0

In [516]:
scaled_df_ts = scaled_df.transpose()
scaled_df_ts

0         1         2    3         4         5         6  \
Height  0.000000  0.076923  0.076923  1.0  0.230769  0.487179  0.538462   
Weight  0.605263  0.605263  0.289474  0.0  0.973684  1.000000  0.578947   
BMI     1.000000  1.000000  1.000000  0.0  1.000000  1.000000  1.000000   

               7         8         9  
Height  0.923077  0.589744  0.153846  
Weight  0.605263  0.421053  0.947368  
BMI     0.000000  0.000000  1.000000

In [526]:
x = scaled_df.iloc[:8,:2].values.transpose()
y = scaled_df.iloc[:8,2:].values.transpose()

xval = scaled_df.iloc[8:,:2].values.transpose()
yval = scaled_df.iloc[8:,2:].values.transpose()

x, x.shape, y, y.shape

(array([[0.        , 0.07692308, 0.07692308, 1.        , 0.23076923,
         0.48717949, 0.53846154, 0.92307692],
        [0.60526316, 0.60526316, 0.28947368, 0.        , 0.97368421,
         1.        , 0.57894737, 0.60526316]]),
 (2, 8),
 array([[1., 1., 1., 0., 1., 1., 1., 0.]]),
 (1, 8))

### Creating Neural Networl Class

In [527]:
def Sigmoid(Z):
    return 1/(1+np.exp(-Z))

def Relu(Z):
    return np.maximum(0,Z)

class Dlnet(object):
    def __init__(self, x, y):
        self.X = x
        self.Y = y
        self.Yh = np.zeros((1, self.Y.shape[1]))
        
        self.dims = [2,3,1]
        
        self.param = {}
        self.ch = {}
        
        self.sam = self.Y.shape[1]
        
    def ninit(self):
        np.random.seed(1)
        self.param['W1'] = np.random.randn(self.dims[1], self.dims[0]) / np.sqrt(self.dims[0])
        self.param['b1'] = np.zeros((self.dims[1],1))
        self.param['W2'] = np.random.randn(self.dims[2], self.dims[1]) / np.sqrt(self.dims[1])
        self.param['b2'] = np.zeros((self.dims[2],1))
        return
   
    def nloss(self,Yh):
        loss = (1./self.sam) * (-np.dot(self.Y,np.log(Yh).T) - np.dot(1-self.Y, np.log(1-Yh).T))    
        return loss
    
    def forward(self):    
        Z1 = self.param['W1'].dot(self.X) + self.param['b1'] 
        A1 = Relu(Z1)
        self.ch['Z1'],self.ch['A1']=Z1,A1
        
        Z2 = self.param['W2'].dot(A1) + self.param['b2']  
        A2 = Sigmoid(Z2)
        self.ch['Z2'],self.ch['A2']=Z2,A2

        self.Yh=A2
        #loss=self.nloss(A2)
        return self.Yh#,loss

In [528]:
x_ = x[:, :1]
y_ = y[:, :1]
x_, x_.shape, y_, y_.shape

(array([[0.        ],
        [0.60526316]]), (2, 1), array([[1.]]), (1, 1))

In [536]:
nn_ = Dlnet(x_, y_)
nn_.ninit()
nn.param

{'W1': array([[ 1.14858562, -0.43257711],
        [-0.37347383, -0.75870339],
        [ 0.6119356 , -1.62743362]]), 'b1': array([[0.],
        [0.],
        [0.]]), 'W2': array([[ 1.00736754, -0.43948301,  0.18419731]]), 'b2': array([[0.]])}

In [535]:
yh = nn_.forward()
yh, yh.shape, nn_.ch

(array([[0.5]]), (1, 1), {'Z1': array([[-0.26182299],
         [-0.45921521],
         [-0.98502561]]), 'A1': array([[0.],
         [0.],
         [0.]]), 'Z2': array([[0.]]), 'A2': array([[0.5]])})

In [530]:
x, x.shape, y, y.shape

(array([[0.        , 0.07692308, 0.07692308, 1.        , 0.23076923,
         0.48717949, 0.53846154, 0.92307692],
        [0.60526316, 0.60526316, 0.28947368, 0.        , 0.97368421,
         1.        , 0.57894737, 0.60526316]]),
 (2, 8),
 array([[1., 1., 1., 0., 1., 1., 1., 0.]]),
 (1, 8))

In [533]:
nn = Dlnet(x,y)
nn.ninit()
yh = nn.forward()
yh, yh.shape, nn.ch

(array([[0.5       , 0.5       , 0.5       , 0.78070248, 0.5       ,
         0.53193792, 0.59163808, 0.69089188]]),
 (1, 8),
 {'Z1': array([[-0.26182299, -0.17347025, -0.03686695,  1.14858562, -0.15613528,
           0.12699025,  0.3680298 ,  0.79840989],
         [-0.45921521, -0.48794396, -0.24835342, -0.37347383, -0.82492378,
          -0.94065218, -0.64035062, -0.80396028],
         [-0.98502561, -0.93795364, -0.42402724,  0.6119356 , -1.44339051,
          -1.32931115, -0.61269463, -0.42016198]]),
  'A1': array([[0.        , 0.        , 0.        , 1.14858562, 0.        ,
          0.12699025, 0.3680298 , 0.79840989],
         [0.        , 0.        , 0.        , 0.        , 0.        ,
          0.        , 0.        , 0.        ],
         [0.        , 0.        , 0.        , 0.6119356 , 0.        ,
          0.        , 0.        , 0.        ]]),
  'Z2': array([[0.        , 0.        , 0.        , 1.26976476, 0.        ,
          0.12792585, 0.37074128, 0.80429221]]),
  'A2':

In [509]:
def mse(y_hat, y):
    return ((yh - y)**2).mean()

mse(yh, y)

0.3090836886229291